version: "3.8"

services:
  database:
    image: postgres:15
    container_name: bookhub-database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookhub
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: bookhub-backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=bookhub
    volumes:
      - ./backend:/app
    depends_on:
      - database
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: bookhub-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  db_data:
