name: Backend CD Pipeline
on:
  push:
    branches: [ "develop", "main" ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/your-backend-image

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to ACR
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.bookhubacr.azurecr.io}}
          username: ${{ secrets.bo
          password: ${{ secrets.j2g9H8S43MAE0Fb+B2dT4U2vZN7T1nRv6YIX0H/ZLk+ACRBHoziN}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest

      - name: Scan with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGE_NAME }}:latest
          format: 'table'
          exit-code: '0'

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'bookhub-backend'
          package: ./Book_Hub/backend
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}