name: CD to Production

on:
  push:
    branches:
      - main

  workflow_dispatch: {}  # Manual trigger (optional)

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    environment: production  # Optional: protects prod deploy with manual approval

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install frontend dependencies
      working-directory: Book_Hub/frontend
      run: npm ci

    - name: Run npm audit
      working-directory: Book_Hub/frontend
      run: npm audit --audit-level=high

    - name: Build frontend
      working-directory: Book_Hub/frontend
      run: npm run build

    - name: Build Docker image (frontend)
      working-directory: Book_Hub/frontend
      run: docker build -t bookhub-frontend:prod .

    - name: Install Trivy
      run: |
        sudo apt-get update
        sudo apt-get install -y wget apt-transport-https gnupg lsb-release
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
        echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update
        sudo apt-get install -y trivy

    - name: Run Trivy scan
      run: trivy image --severity CRITICAL,HIGH bookhub-frontend:prod

    - name: Deploy to Azure Production
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME_PROD }}
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_PROD }}
        package: Book_Hub/frontend
