name: Deploy to Staging

on:
  push:
    branches: [develop]

env:
  APP_NAME: "bookhub-frontend"
  SLOT_NAME: "staging"
  RESOURCE_GROUP: "bookhub-rg"
  ACR_NAME: "bookhubacr"
  NODE_VERSION: "18"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures package-lock.json is fetched

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: |
          # First ensure package-lock.json exists
          if [ ! -f "package-lock.json" ]; then
            npm install --package-lock-only
          fi
          npm ci --strict-peer-deps
          npm cache clean --force

      - name: Build app
        run: npm run build

      - name: Login to ACR
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and push image
        run: |
          docker build -t ${{ env.ACR_NAME }}.azurecr.io/${{ env.APP_NAME }}:${{ github.sha }} .
          docker push ${{ env.ACR_NAME }}.azurecr.io/${{ env.APP_NAME }}:${{ github.sha }}

      - name: Deploy to staging slot
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.APP_NAME }}
          slot-name: ${{ env.SLOT_NAME }}
          resource-group: ${{ env.RESOURCE_GROUP }}
          images: '${{ env.ACR_NAME }}.azurecr.io/${{ env.APP_NAME }}:${{ github.sha }}'